version: '3.7'
services:
  battle-ship-api:
    build:
      context: .
    container_name: battle-ship-api
    working_dir: /usr/app/
    volumes:
      - /usr/app/node_modules/
      - .:/usr/app
    ports:
      - '3333:3000'
    networks:
      - battle-ship-networks
    command: ['npm', 'start']

  mongodb:
    image: mongo:4.2.3
    container_name: battle-ship-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    networks:
      - battle-ship-networks
    ports:
      - '28888:27017'

networks:
  battle-ship-networks:
    driver: bridge
